language: python
matrix:
  include:
  - python: 2.6
    env:
    - SCIPYSPEC===0.12.0
  - python: 2.7
    env:
    - SCIPYSPEC===0.12.0
    - secure: WxnAQRmA61mfHCw7wkzp+77ia2RKh111lZPm3kzeVlgARXWMWDlUp3jiTkFb5SagcTBh3TOVI+5/HUddjKLjRQJz4yvA3LkfoJ2PzBz7jGG6nvr16cknkJemD6kPZbqJC3AhGcgUKlbQXsQvu9dN6bQCDU5SolEFSNUY+QV/ozw=
    - secure: P5pPcavMSCel03a00r63dbO6lx/YFMxxLuGHXVpIvjPuN8WiXDyTI/0aKVGXORvSmvtyqRK07DSdzP/qyoUa2CtpVtbYEQDWJj2uXlufnE6L3rzR8R2oUt1v4zF8LHJ6gqzUKqi4YCg4KCzE6V6ANjsrJKKiiXCIdwfFYmRzpPU=
    - BOB_DOCUMENTATION_SERVER=https://www.idiap.ch/software/bob/docs/latest/bioidiap/%s/master
  - python: 3.2
    env:
    - NUMPYSPEC===1.8.0
    - SCIPYSPEC===0.13.1
  - python: 3.3
    env:
    - NUMPYSPEC===1.8.0
    - SCIPYSPEC===0.13.1
before_install:
- sudo add-apt-repository -y ppa:biometrics/bob
- sudo apt-get update -qq
- sudo apt-get install -qq --force-yes libboost-all-dev libblitz1-dev libatlas-dev libatlas-base-dev liblapack-dev gfortran texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
- if [ -n "${NUMPYSPEC}" ]; then pip install --find-links http://wheels.astropy.org/ --find-links http://wheels2.astropy.org/ --use-wheel numpy$NUMPYSPEC; fi
- pip install --find-links http://wheels.astropy.org/ --find-links http://wheels2.astropy.org/ --use-wheel scipy$SCIPYSPEC sphinx nose==1.3.0 jinja2==2.6 cpp-coveralls pygments==1.6
install:
- python bootstrap-buildout.py
- CFLAGS=-coverage ./bin/buildout
script:
- ./bin/python -c 'from bob.ap import get_config; print(get_config())'
- ./bin/coverage run --source=bob.ap ./bin/nosetests -sv
- ./bin/sphinx-build -b doctest doc sphinx
- ./bin/sphinx-build -b html doc sphinx
after_success:
- coveralls --build-root=`pwd` --exclude=src --exclude-pattern=".*Compiler.*"
- ./src/bob.extension/scripts/upload-sphinx.sh
